baseurl = "https://tsia.netlify.com"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5
theme = "hugo-theme-hello-friend"
[languages.en]
copyright = ""
dateFormatList = "2006-01-02"
dateFormatSingle = "2006-01-02"
keywords = ""
menuMore = "Show more"
minuteReadingTime = "min read"
newerPosts = "Newer posts"
olderPosts = "Older posts"
readMore = "Read more"
readOtherPosts = "Read other posts"
subtitle = "A simple theme for Hugo"
title = "佇遮"
writtenBy = "Written by"
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "showcase"
name = "Showcase"
url = "/showcase"
[languages.en.params.logo]
logoHomeLink = "/"
logoText = "hello friend"
[params]
  contentTypeName = "post"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "佇遮"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

