baseURL = "https://tsia.netlify.com"
theme = "hugo-theme-hello-friend-ng"
title = "佇遮"
DefaultContentLanguage = "en"

PygmentsCodeFences = true
PygmentsStyle = "monokai"
archetypeDir = "archetypes"
buildDrafts = false
buildExpored = false
buildFuture = false
canonifyURLs = true
contentDir = "content"
dataDir = "data"
disable404 = false
disableHugoGeneratorInject = false
disableRSS = false
disableSitemap = false
enableEmoji = true
enableGitInfo = false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true
layoutDir = "layouts"
publishDir = "public"
rssLimit = 100

[author]
name = "ann"
[blackfriday]
hrefTargetBlank = true
[languages.en]
subtitle = "Hello Friend NG Theme"
weight = 1
[[menu.main]]
identifier = "about"
name = "About"
url = "about/"
weight = 3
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "posts/"
weight = 2
[[menu.main]]
identifier = "meo"
name = "meo"
url = "test/"
weight = 1
[params]
contentTypeName = "posts"
customCSS = []
customJS = []
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
dateformShort = "Jan 2"
defaultTheme = "dark"
description = "Nice theme for homepages and blogs"
disableReadOtherPosts = false
homeSubtitle = "Hello Friend"
images = [""]
justifyContent = false
keywords = ""
themeColor = "#0c69c7"
[params.favicon.color]
mask = "#0c69c7"
msapplication = "#0c69c7"
theme = "#0c69c7"
[params.logo]
logoHomeLink = "/"
logoText = "$ cd /home/"
[[params.social]]
name = "twitter"
url = "https://twitter.com/"
[[params.social]]
name = "email"
url = "mailto:nobody@example.com"
[[params.social]]
name = "github"
url = "https://github.com/"
[permalinks]
posts = "/posts/:year/:month/:title/"
[taxonomies]
category = "categories"
tag = "tags"
