baseURL = "https://tsia.netlify.com"
theme = "minimal"
title = "佇遮"
languageCode = "en"     

disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
  url = "/tags"
  name = "Tags"
  weight = 4

[[menu.main]]
    url = "/categories"
    name = "Categories"
    weight = 5


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

   
[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 3

[[menu.icon]]
    url = "https://facebook.com/username"
        name = "facebook"
    weight = 4

[[menu.icon]]
    url = "https://www.instagram.com/username"
    name = "instagram"
    weight = 5

[[menu.icon]]
    url = "https://www.youtube.com/channel/username"
    name = "youtube"
    weight = 6

[[menu.icon]]
    url = "https://medium.com/@username"
    name = "medium"
    weight = 7

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "stack-overflow"
    weight = 8
