baseURL = "https://tsia.netlify.com"
languageCode = "en-us"
title = "佇遮"
author = "安"
pygmentsCodeFences = true
theme = "hugo-theme-base16"
paginate = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  hero = "Base16"
  message = "Sub Title message"
  descriptions = "Blog description"
  twitter = "twitter user"